### PR TITLE
Added method getFile() into Snapshot class.

### PR DESCRIPTION
**Pull request by danylovolokh**
This gives us the ability to work with File class and not only with InputStream.
Since DiskLruCache is caching data in files it is useful to manipulate with File-s.

Example:
I used this cache to store .mp4 files. 
Android MediaPlayer class doesn't work with InputStream so I used absolute path of File to start playback. But to get File from cache I've added this code.

### CODE REVIEW

**Comment by swankjesse** [comment]
I think this breaks some assumptions. For example, the file you’re accessing could be evicted while you’re accessing it. If you want this use case, you probably don’t want this library.

**Comment by danylovolokh** [comment]
Can it (file) be evicted while I'm accessing it via InputStream?

**Comment by danylovolokh** [comment]
Hi @swankjesse, 
Thanks for quick reply.

I tried to understand which assumptions I broke with this changes, please correct me if I'm wrong:
- If we shouldn't use the File after entry was evicted, we should not use InputStream ether.
- Snapshot means that this is the data of the entry at the moment of it's creation. So this assumes that actual data can be changed since it was created.
- We have to use data accurately and make null checks and other stuff (like File.exists()), because we don't know if the data is still valid.

I've added the Unit test to verify that accessing evicted entry is forbidden.
Doesn't matter if it''s InputStream or File. 

@swankjesse could you please review my changes again?
Thank you.

**Comment by swankjesse** [comment]
The reason the previous change was safe is that we were opening the InputStreams eagerly. That prevents the underlying bytes from being released until the stream is closed. `File` doesn’t have this capability.

If you want this behavior I recommend you fork the project. There may be a substantial amount of code necessary to make that work, including new APIs.

**Comment by danylovolokh** [comment]
@swankjesse 
"It prevents the underlying bytes from being released", but it throws IOException when trying to read it.
The message says "Stream Closed".

So InputStream is opened at the moment of creating Snapshot in synchronized method.
After we exit this method removing Entry will cause IOException while trying to read recently opened InputStream.

So what is the case that you are handling with opening InputStreams immediately ?

**Comment by swankjesse** [comment]
Here’s an example.

```
    long cacheSize = 1024 * 1024 * 2;
    DiskLruCache cache = new DiskLruCache(
        FileSystem.SYSTEM, cacheDir, appVersion, 1, cacheSize, executor);

    ByteString data = ByteString.of(new byte[1024 * 1024]);

    DiskLruCache.Editor editor = cache.edit("a");
    BufferedSink sink = Okio.buffer(editor.newSink(0));
    sink.write(data);
    sink.close();
    editor.commit();

    DiskLruCache.Snapshot snapshot = cache.get("a");

    cache.evictAll();

    BufferedSource source = Okio.buffer(snapshot.getSource(0));
    assertEquals(data, source.readByteString());
```

**Comment by danylovolokh** [comment]
@swankjesse 
- The class DiskLruCache from this project doesn't have method "evictAll"
- The class Snapshot doesn't have method "getSource"

Is there a possibility you are using different DiskLruCache, the one from com.squareup.okhttp.internal ?

**Comment by swankjesse** [comment]
Yep. You can translate the example if you like, but the consequence is the same. Deleting a file doesn’t impact existing InputStreams on that File.

**Comment by danylovolokh** [comment]
@swankjesse 
I did that in my unit test.
Actually it proves the opposite, probably there is a difference between this library and DiskLruCache from com.squareup.okhttp.internal.

Here is the code snipped.

``` java
@Test public void tryToUseDataAfterEvicted() throws Exception{
    cache.close();
    cache = DiskLruCache.open(cacheDir, appVersion, 2, 3);

    set("a", "a", "aa"); // size 3
    assertThat(cache.size()).isEqualTo(3);

    DiskLruCache.Snapshot snapshot = cache.get("a");
    String stringAt_a = snapshot.getString(0);
    File fileAtEntry = snapshot.getFile(0);

    // assert string at "a" is correct
    assertThat(stringAt_a).isEqualTo("a");
    // assert that file at "a" exists
    assertThat(fileAtEntry.exists()).isTrue();

    // Causing the size to grow to 4 should evict 'a'.
    set("b", "b", "bbbb");
    cache.flush();

    String stringAtAfterEvict = null;
    try {
      stringAtAfterEvict = snapshot.getString(0);
    } catch (IOException exception){
      assertThat(exception.getMessage()).isEqualTo("Stream Closed");
    }

    // assert that we failed to get string
    assertThat(stringAtAfterEvict).isNull();

    // assert that file doesn't exist after evict
    File fileAtAfterEvict = snapshot.getFile(0);
    assertThat(fileAtAfterEvict.exists()).isFalse();
}
```

**Comment by hey99xx** [comment]
@danylovolokh , I believe what @swankjesse is referring to is the behavior explained in http://stackoverflow.com/questions/4693968/is-there-an-existing-fileinputstream-delete-on-close

I do understand the concern, but still, this would be a very useful for some projects, where 3p libraries only accept files rather than input streams.

@sjudd has added this method in his fork of this project; I wonder if he decided to disregard this safety net https://github.com/sjudd/DiskLruCache/commit/cecc9bb82127809a8fb5571983029d96e9468ef9

**Pull request closed without merging**
